"""initial schema

Revision ID: a85332623f77
Revises: 
Create Date: 2026-07-10 18:14:19.310859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85332623f77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_state',
    sa.Column('subreddit_name', sa.String(length=64), nullable=False),
    sa.Column('last_fetched_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subreddit_name')
    )
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id', name='uq_posts_reddit_id')
    )
    op.create_index(op.f('ix_posts_reddit_id'), 'posts', ['reddit_id'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vader_score', sa.Float(), nullable=False),
    sa.Column('transformer_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_posts_reddit_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('topics')
    op.drop_table('subreddits')
    op.drop_table('pipeline_state')
    # ### end Alembic commands ###
